# Use the official Node.js image.
FROM node:16-alpine

# Set the working directory.
WORKDIR /app

# Install dependencies.
COPY package*.json ./
RUN npm install

# Copy the source code.
COPY . .

# Expose the app port.
EXPOSE 5000

# Start the application.
CMD ["node", "server.js"]
